# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

Rcpp_norm <- function(a) {
    .Call('_dMrs_Rcpp_norm', PACKAGE = 'dMrs', a)
}

Rcpp_max_abs_diff <- function(aa, bb) {
    .Call('_dMrs_Rcpp_max_abs_diff', PACKAGE = 'dMrs', aa, bb)
}

Rcpp_logSumExp <- function(log_x) {
    .Call('_dMrs_Rcpp_logSumExp', PACKAGE = 'dMrs', log_x)
}

prt_vec <- function(aa) {
    invisible(.Call('_dMrs_prt_vec', PACKAGE = 'dMrs', aa))
}

calc_expweibull_CDF_PDF <- function(XX, LAM, ALP, KAP) {
    .Call('_dMrs_calc_expweibull_CDF_PDF', PACKAGE = 'dMrs', XX, LAM, ALP, KAP)
}

calc_copula <- function(F1, F2, copula, THETA) {
    .Call('_dMrs_calc_copula', PACKAGE = 'dMrs', F1, F2, copula, THETA)
}

calc_copula_dens <- function(D1, D2, F1, F2, copula, THETA, F_T1_T2) {
    .Call('_dMrs_calc_copula_dens', PACKAGE = 'dMrs', D1, D2, F1, F2, copula, THETA, F_T1_T2)
}

calc_copula_CDF_PDF <- function(D1, D2, F1, F2, copula, THETA) {
    .Call('_dMrs_calc_copula_CDF_PDF', PACKAGE = 'dMrs', D1, D2, F1, F2, copula, THETA)
}

dMrs_cLL <- function(XX, DELTA, D2, S2, PARS, copula, verb = FALSE) {
    .Call('_dMrs_dMrs_cLL', PACKAGE = 'dMrs', XX, DELTA, D2, S2, PARS, copula, verb)
}

dMrs_cGRAD <- function(XX, DELTA, D2, S2, PARS, copula, upPARS) {
    .Call('_dMrs_dMrs_cGRAD', PACKAGE = 'dMrs', XX, DELTA, D2, S2, PARS, copula, upPARS)
}

dMrs_cHESS <- function(XX, DELTA, D2, S2, PARS, copula, upPARS) {
    .Call('_dMrs_dMrs_cHESS', PACKAGE = 'dMrs', XX, DELTA, D2, S2, PARS, copula, upPARS)
}

dMrs_BFGS <- function(XX, DELTA, D2, S2, PARS, copula, upPARS, max_iter = 4e3L, eps = 1e-7, verb = TRUE) {
    invisible(.Call('_dMrs_dMrs_BFGS', PACKAGE = 'dMrs', XX, DELTA, D2, S2, PARS, copula, upPARS, max_iter, eps, verb))
}

dMrs_NR <- function(XX, DELTA, D2, S2, PARS, copula, upPARS, max_iter = 2e2L, eps = 5e-2, mult = 5L, verb = TRUE) {
    invisible(.Call('_dMrs_dMrs_NR', PACKAGE = 'dMrs', XX, DELTA, D2, S2, PARS, copula, upPARS, max_iter, eps, mult, verb))
}

dMrs_GRID <- function(XX, DELTA, D2, S2, log_THETA, log_ALPHA, log_LAMBDA, unc_KAPPA, copula, verb = FALSE, ncores = 1L) {
    .Call('_dMrs_dMrs_GRID', PACKAGE = 'dMrs', XX, DELTA, D2, S2, log_THETA, log_ALPHA, log_LAMBDA, unc_KAPPA, copula, verb, ncores)
}

dMrs_MATCH <- function(wDAT, rDAT, ncores = 1L, verb = TRUE) {
    .Call('_dMrs_dMrs_MATCH', PACKAGE = 'dMrs', wDAT, rDAT, ncores, verb)
}

