# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

Rcpp_norm <- function(a) {
    .Call('_dMrs_Rcpp_norm', PACKAGE = 'dMrs', a)
}

Rcpp_max_abs_diff <- function(aa, bb) {
    .Call('_dMrs_Rcpp_max_abs_diff', PACKAGE = 'dMrs', aa, bb)
}

Rcpp_logSumExp <- function(log_x) {
    .Call('_dMrs_Rcpp_logSumExp', PACKAGE = 'dMrs', log_x)
}

dMrs_cLL <- function(XX, DELTA, D2, S2, PARS, copula, show = FALSE) {
    .Call('_dMrs_dMrs_cLL', PACKAGE = 'dMrs', XX, DELTA, D2, S2, PARS, copula, show)
}

dMrs_cGRAD <- function(XX, DELTA, D2, S2, PARS, copula, upPARS) {
    .Call('_dMrs_dMrs_cGRAD', PACKAGE = 'dMrs', XX, DELTA, D2, S2, PARS, copula, upPARS)
}

dMrs_cHESS <- function(XX, DELTA, D2, S2, PARS, copula, upPARS) {
    .Call('_dMrs_dMrs_cHESS', PACKAGE = 'dMrs', XX, DELTA, D2, S2, PARS, copula, upPARS)
}

dMrs_BFGS <- function(XX, DELTA, D2, S2, PARS, copula, upPARS, max_iter = 4e3L, eps = 1e-7, show = TRUE) {
    invisible(.Call('_dMrs_dMrs_BFGS', PACKAGE = 'dMrs', XX, DELTA, D2, S2, PARS, copula, upPARS, max_iter, eps, show))
}

dMrs_GRID <- function(XX, DELTA, D2, S2, log_THETA, log_ALPHA, log_LAMBDA, unc_KAPPA, copula, show = FALSE, ncores = 1L) {
    .Call('_dMrs_dMrs_GRID', PACKAGE = 'dMrs', XX, DELTA, D2, S2, log_THETA, log_ALPHA, log_LAMBDA, unc_KAPPA, copula, show, ncores)
}

dMrs_MATCH <- function(wDAT, rDAT, ncores = 1L, show = TRUE) {
    .Call('_dMrs_dMrs_MATCH', PACKAGE = 'dMrs', wDAT, rDAT, ncores, show)
}

